version: '3.8'

services:
  ai-chat-platform-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AI_BASE_URL=${AI_BASE_URL}
      - TENANT_UUID=${TENANT_UUID}
      - LOGIN_PATH=${LOGIN_PATH}
      - MAX_MESSAGE_LENGTH=10000
      - MAX_FILE_SIZE=5242880
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX_REQUESTS=100
      - SESSION_TIMEOUT=1800000
      - NEXT_PUBLIC_APP_NAME=AI Chat Platform (Dev)
      - NEXT_PUBLIC_APP_VERSION=1.0.0-dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: unless-stopped
    networks:
      - ai-chat-dev-network

networks:
  ai-chat-dev-network:
    driver: bridge
